#!/usr/bin/env python3
"""Install the Superbeads SessionStart adapter into one project."""

from __future__ import annotations

import argparse
import json
import os
import stat
import subprocess
import tempfile
from pathlib import Path


GENERATED_MARKER = "Generated by superbeads project-init"
EXCLUDE_BEGIN = "# BEGIN superbeads project-init"
EXCLUDE_END = "# END superbeads project-init"
MATCHER = "startup|resume|clear|compact"


def fail(message: str) -> None:
    raise SystemExit(f"error: {message}")


def git(project: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(project), *args],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        fail(result.stderr.strip() or f"git {' '.join(args)} failed")
    return result.stdout.strip()


def project_root(requested: Path) -> Path:
    requested = requested.resolve()
    return Path(git(requested, "rev-parse", "--show-toplevel")).resolve()


def refuse_symlinks(project: Path, target: Path) -> None:
    current = target
    while current != project:
        if current.is_symlink():
            fail(f"refusing symlink target: {current}")
        current = current.parent
    if project.is_symlink():
        fail(f"refusing symlink project root: {project}")


def atomic_write(path: Path, content: str | bytes, mode: int = 0o644) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    data = content.encode("utf-8") if isinstance(content, str) else content
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def source_files() -> tuple[Path, Path]:
    script = Path(__file__).resolve()
    skills_dir = script.parents[2]
    using_superpowers = skills_dir / "using-superpowers" / "SKILL.md"
    runtime_candidates = [
        script.parents[1] / "assets" / "session-start",
        script.parents[3] / "hooks" / "session-start",
        Path.home() / ".claude" / "skills" / "project-init" / "assets" / "session-start",
        Path.home() / ".codex" / "skills" / "project-init" / "assets" / "session-start",
        Path.home()
        / ".config"
        / "opencode"
        / "skills"
        / "project-init"
        / "assets"
        / "session-start",
    ]
    runtime = next((path for path in runtime_candidates if path.is_file()), None)
    if runtime is None:
        fail("SessionStart runtime is unavailable; reinstall Superbeads, then rerun project-init")
    if not using_superpowers.is_file():
        fail(f"using-superpowers skill is unavailable beside project-init: {using_superpowers}")
    return runtime, using_superpowers


def is_tracked(project: Path, relative: Path) -> bool:
    result = subprocess.run(
        ["git", "-C", str(project), "ls-files", "--error-unmatch", str(relative)],
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    return result.returncode == 0


def load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        fail(f"cannot read valid JSON from {path}: {error}")
    if not isinstance(value, dict):
        fail(f"expected a JSON object in {path}")
    return value


def strip_project_hook(data: dict) -> tuple[dict, bool]:
    hooks = data.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        fail("existing 'hooks' value is not an object")
    groups = hooks.setdefault("SessionStart", [])
    if not isinstance(groups, list):
        fail("existing hooks.SessionStart value is not a list")

    kept = []
    removed = False
    for group in groups:
        if not isinstance(group, dict):
            kept.append(group)
            continue
        handlers = group.get("hooks", [])
        if not isinstance(handlers, list):
            fail("existing SessionStart group 'hooks' value is not a list")
        kept_handlers = [
            handler
            for handler in handlers
            if not (
                isinstance(handler, dict)
                and ".superbeads/hooks/session-start" in handler.get("command", "")
            )
        ]
        if len(kept_handlers) != len(handlers):
            removed = True
        if kept_handlers:
            group = dict(group)
            group["hooks"] = kept_handlers
            kept.append(group)
    if kept:
        hooks["SessionStart"] = kept
    else:
        hooks.pop("SessionStart", None)
    if not hooks:
        data.pop("hooks", None)
    return data, removed


def merge_hook(data: dict, command: str) -> dict:
    data, _ = strip_project_hook(data)
    hooks = data.setdefault("hooks", {})
    groups = hooks.setdefault("SessionStart", [])
    groups.append(
        {
            "matcher": MATCHER,
            "hooks": [
                {
                    "type": "command",
                    "command": command,
                    "async": False,
                }
            ],
        }
    )
    return data


def json_target(project: Path, harness: str, tracked: bool) -> tuple[Path, str]:
    if harness == "claude":
        relative = Path(".claude/settings.json" if tracked else ".claude/settings.local.json")
        command = (
            'CLAUDE_PLUGIN_ROOT="$CLAUDE_PROJECT_DIR/.superbeads" '
            '"$CLAUDE_PROJECT_DIR/.superbeads/hooks/session-start"'
        )
    elif harness == "codex":
        relative = Path(".codex/hooks.json")
        command = (
            'CODEX_PLUGIN_ROOT="$(git rev-parse --show-toplevel)/.superbeads" '
            '"$(git rev-parse --show-toplevel)/.superbeads/hooks/session-start"'
        )
    else:
        fail(f"JSON hooks are unsupported for harness: {harness}")
    return project / relative, command


def opencode_plugin() -> str:
    return f"""// {GENERATED_MARKER}
import {{ execFileSync }} from "node:child_process"
import {{ join }} from "node:path"

export const BeadsSuperpowers = async (context: {{ worktree?: string; directory?: string }}) => {{
  const root = context.worktree || context.directory || process.cwd()
  const hook = join(root, ".superbeads", "hooks", "session-start")
  const seen = new Set<string>()
  const compose = () =>
    execFileSync(hook, ["--emit-plain"], {{ encoding: "utf-8", timeout: 10000 }}).trim()

  return {{
    "chat.message": async (input: {{ sessionID: string }}, output: {{ parts: any[] }}) => {{
      if (seen.has(input.sessionID)) return
      seen.add(input.sessionID)
      const text = compose()
      if (text) output.parts.unshift({{ type: "text", text }})
    }},
    "experimental.session.compacting": async (
      _input: unknown,
      output: {{ context: string[] }}
    ) => {{
      const text = compose()
      if (text) output.context.push(text)
    }},
  }}
}}
"""


def update_excludes(project: Path, patterns: set[str], tracked: bool) -> None:
    exclude_raw = git(project, "rev-parse", "--git-path", "info/exclude")
    exclude = Path(exclude_raw)
    if not exclude.is_absolute():
        exclude = project / exclude
    existing = exclude.read_text(encoding="utf-8") if exclude.exists() else ""
    owned_patterns: set[str] = set()
    before, marker, remainder = existing.partition(EXCLUDE_BEGIN)
    if marker:
        owned, end, after = remainder.partition(EXCLUDE_END)
        if not end:
            fail(f"unterminated Superbeads block in {exclude}")
        owned_patterns.update(
            line.strip()
            for line in owned.splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        )
        existing = before.rstrip("\n") + ("\n" if before.strip() else "") + after.lstrip("\n")
    if tracked:
        owned_patterns.difference_update(patterns)
    else:
        owned_patterns.update(patterns)
    if owned_patterns:
        block = "\n".join([EXCLUDE_BEGIN, *sorted(owned_patterns), EXCLUDE_END, ""])
        existing = existing.rstrip("\n") + ("\n" if existing.strip() else "") + block
    atomic_write(exclude, existing)


def remove_local_claude_adapter(project: Path) -> None:
    local_settings = project / ".claude/settings.local.json"
    if not local_settings.exists():
        return
    refuse_symlinks(project, local_settings)
    data, removed = strip_project_hook(load_json(local_settings))
    if not removed:
        return
    if data:
        atomic_write(local_settings, json.dumps(data, indent=2) + "\n")
    else:
        local_settings.unlink()


def install(project: Path, harness: str, tracked: bool) -> None:
    project = project_root(project)
    runtime_source, skill_source = source_files()
    runtime_target = project / ".superbeads/hooks/session-start"
    skill_target = project / ".superbeads/skills/using-superpowers/SKILL.md"

    if harness == "opencode":
        config_target = project / ".opencode/plugins/superbeads-plugin.ts"
        config_content: str | None = opencode_plugin()
    else:
        config_target, command = json_target(project, harness, tracked)
        config_content = json.dumps(merge_hook(load_json(config_target), command), indent=2) + "\n"

    targets = [runtime_target, skill_target, config_target]
    for target in targets:
        refuse_symlinks(project, target)
        relative = target.relative_to(project)
        if not tracked and is_tracked(project, relative):
            fail(f"{relative} is tracked; rerun only after the user explicitly requests --tracked")

    if harness == "opencode" and config_target.exists():
        existing = config_target.read_text(encoding="utf-8")
        if GENERATED_MARKER not in existing:
            fail(f"refusing to replace foreign OpenCode plugin: {config_target}")

    ignore_patterns = {
        "/.superbeads/",
        f"/{config_target.relative_to(project).as_posix()}",
    }
    update_excludes(project, ignore_patterns, tracked)
    if tracked and harness == "claude":
        remove_local_claude_adapter(project)
    runtime_mode = (
        stat.S_IRWXU
        | stat.S_IRGRP
        | stat.S_IXGRP
        | stat.S_IROTH
        | stat.S_IXOTH
    )
    atomic_write(runtime_target, runtime_source.read_bytes(), runtime_mode)
    atomic_write(skill_target, skill_source.read_bytes())
    atomic_write(config_target, config_content or "")

    mode = "tracked" if tracked else "local-only"
    print(f"Installed {mode} Superbeads SessionStart support for {harness} in {project}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", type=Path, default=Path.cwd())
    parser.add_argument("--harness", choices=("claude", "codex", "opencode"), required=True)
    parser.add_argument("--tracked", action="store_true")
    args = parser.parse_args()
    install(args.project, args.harness, args.tracked)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
