#!/usr/bin/env bash
# Project-init owns SessionStart activation; default installs stay local to one checkout.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
INSTALLER="$ROOT/skills/project-init/scripts/install-session-hook.py"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
fail=0

new_repo() {
  local name="$1"
  local repo="$TMP/$name"
  mkdir -p "$repo"
  git -C "$repo" init -q
  printf '%s\n' "$repo"
}

run_installer() {
  local repo="$1" harness="$2"
  shift 2
  python3 "$INSTALLER" --project "$repo" --harness "$harness" "$@"
}

expect_file() {
  if [ -f "$1" ]; then
    echo "PASS: file $1"
  else
    echo "FAIL: missing $1"
    fail=1
  fi
}

expect_json_hook() {
  local path="$1"
  if python3 - "$path" <<'PY'
import json
import sys

data = json.load(open(sys.argv[1], encoding="utf-8"))
groups = data.get("hooks", {}).get("SessionStart", [])
commands = [
    hook.get("command", "")
    for group in groups
    for hook in group.get("hooks", [])
]
raise SystemExit(0 if sum(".superbeads/hooks/session-start" in command for command in commands) == 1 else 1)
PY
  then
    echo "PASS: one project-local SessionStart hook in $path"
  else
    echo "FAIL: expected one project-local SessionStart hook in $path"
    fail=1
  fi
}

expect_clean() {
  local repo="$1"
  if [ -z "$(git -C "$repo" status --short)" ]; then
    echo "PASS: local install leaves git status clean"
  else
    echo "FAIL: local install leaked into git status"
    git -C "$repo" status --short
    fail=1
  fi
}

claude_repo=$(new_repo claude-local)
run_installer "$claude_repo" claude || fail=1
run_installer "$claude_repo" claude || fail=1
expect_file "$claude_repo/.superbeads/hooks/session-start"
expect_file "$claude_repo/.superbeads/skills/using-superpowers/SKILL.md"
expect_file "$claude_repo/.claude/settings.local.json"
expect_json_hook "$claude_repo/.claude/settings.local.json"
expect_clean "$claude_repo"
run_installer "$claude_repo" codex || fail=1
all_ignored=1
exclude_path=$(git -C "$claude_repo" rev-parse --git-path info/exclude)
for pattern in "/.claude/settings.local.json" "/.codex/hooks.json" "/.superbeads/"; do
  grep -qxF "$pattern" "$claude_repo/$exclude_path" || all_ignored=0
done
if [ "$all_ignored" -eq 1 ]; then
  echo "PASS: adding a harness preserves all local excludes"
else
  echo "FAIL: adding a harness dropped an existing local exclude"
  fail=1
fi
expect_clean "$claude_repo"
if CLAUDE_PLUGIN_ROOT="$claude_repo/.superbeads" \
  bash "$claude_repo/.superbeads/hooks/session-start" </dev/null 2>/dev/null |
  python3 -m json.tool >/dev/null 2>&1; then
  echo "PASS: copied hook emits valid JSON"
else
  echo "FAIL: copied hook output is invalid"
  fail=1
fi

mixed_repo=$(new_repo claude-mixed-group)
mkdir -p "$mixed_repo/.claude"
cat >"$mixed_repo/.claude/settings.local.json" <<'JSON'
{
  "hooks": {
    "SessionStart": [
      {
        "matcher": "startup",
        "hooks": [
          {
            "type": "command",
            "command": "\"$CLAUDE_PROJECT_DIR/.superbeads/hooks/session-start\""
          },
          {
            "type": "command",
            "command": "./keep-foreign-hook"
          }
        ]
      }
    ]
  }
}
JSON
run_installer "$mixed_repo" claude || fail=1
if grep -qF "./keep-foreign-hook" "$mixed_repo/.claude/settings.local.json"; then
  echo "PASS: updating a mixed hook group preserves foreign handlers"
else
  echo "FAIL: updating a mixed hook group discarded a foreign handler"
  fail=1
fi
expect_json_hook "$mixed_repo/.claude/settings.local.json"

codex_repo=$(new_repo codex-local)
run_installer "$codex_repo" codex || fail=1
expect_file "$codex_repo/.codex/hooks.json"
expect_json_hook "$codex_repo/.codex/hooks.json"
expect_clean "$codex_repo"

opencode_repo=$(new_repo opencode-local)
run_installer "$opencode_repo" opencode || fail=1
expect_file "$opencode_repo/.opencode/plugins/superbeads-plugin.ts"
if grep -q "Generated by superbeads project-init" "$opencode_repo/.opencode/plugins/superbeads-plugin.ts"; then
  echo "PASS: OpenCode project plugin is generated"
else
  echo "FAIL: OpenCode project plugin marker missing"
  fail=1
fi
expect_clean "$opencode_repo"

tracked_repo=$(new_repo claude-tracked)
run_installer "$tracked_repo" claude --tracked || fail=1
expect_file "$tracked_repo/.claude/settings.json"
expect_json_hook "$tracked_repo/.claude/settings.json"
if [ -n "$(git -C "$tracked_repo" status --short)" ]; then
  echo "PASS: tracked install is visible to git"
else
  echo "FAIL: tracked install was hidden from git"
  fail=1
fi

converted_repo=$(new_repo claude-converted)
run_installer "$converted_repo" claude || fail=1
run_installer "$converted_repo" claude --tracked || fail=1
expect_file "$converted_repo/.claude/settings.json"
if [ ! -e "$converted_repo/.claude/settings.local.json" ]; then
  echo "PASS: tracked conversion removes the generated local adapter"
else
  echo "FAIL: tracked conversion left a duplicate local adapter"
  fail=1
fi
converted_status=$(git -C "$converted_repo" status --short --untracked-files=all)
if echo "$converted_status" | grep -q ".superbeads/" &&
  echo "$converted_status" | grep -q ".claude/settings.json"; then
  echo "PASS: tracked conversion exposes shared files"
else
  echo "FAIL: tracked conversion did not expose shared files"
  echo "$converted_status"
  fail=1
fi

[ "$fail" -eq 0 ] && echo "PASS: project-local hook installation"
exit "$fail"
